### ISSUE TITLE
`st_hatched_polygon()` does not seem to properly account for `MULTIPOLYGON`

### ISSUE THREAD

**Issue by statnmap** [rpkgs/gg.layers#3]
As opened there by @melissa-gaughan : https://github.com/statnmap/HatchedPolygons/issues/10#issuecomment-1885680541
`st_hatched_polygon()` does not work with the `MULTIPOLYGON` from `mapview::franconia`.

The problem arises in `polygon.fullhatch()` applied on a list which arises because a multipolygon is a list of a list.

```
Browse[4]>   lines.hatch <- polygon.fullhatch(geom[[1]], density = density, 
+     angle = angle, fillOddEven = fillOddEven)
Erreur dans x[, 2] : nombre de dimensions incorrect

Browse[4]> geom[[1]]
[[1]]
          [,1]     [,2]
 [1,] 10.92581 49.92507
 [2,] 10.93143 49.92116
 [3,] 10.94067 49.91436
....
```

If I run `st_cast("POLYGON")` before, the function does not fail.  
I do not know if there are some edge cases to account for, like polygons that are supposed to be "holes" inside polygons and that should not be hatched. At least, this is a place to start.

```r
library(sf)
# remotes::install_github("rpkgs/gg.layers")
library(gg.layers)
library(mapview)
library(dplyr)
library(ggplot2)


franconia <- mapview::franconia

hatch_franconia <- franconia %>%
  gg.layers::st_hatched_polygon(density = 10, angle = 45)
#> Error in x[, 2]: incorrect number of dimensions
#> 

hatch_franconia <- franconia %>%
  st_cast("POLYGON") %>%
  gg.layers::st_hatched_polygon(density = 10, angle = 45)
#> Does not fail

ggplot() +
  geom_sf(data = franconia) +
  geom_sf(data = franconia %>% 
            st_cast("POLYGON"), fill = "lightblue", alpha = 0.5) +
  geom_sf(data = hatch_franconia, aes(color = as.character(ID)))
```

![image](https://github.com/rpkgs/gg.layers/assets/21193866/ee9783c7-25fa-4a09-9c83-f12660a2f410)

**Comment by kongdd** [comment]
Thank you @statnmap.
This issue should has been fixed. An if condition was added to `st_hatched_polygon`.
